### ISSUE TITLE
Logo offer

### ISSUE THREAD

**Issue by familqasimov** [SloCompTech/docker-sphinxdocs#2]
Hi, Martin Dagarin

I'm designing for open source projects and I'm trying to expand my design tecnigue with these jobs. I want to design an icon for your project. I have a few ideas in my mind, I hope you accept and I do them. Please let me know if you have any ideas. In this way, we create a logo that will make you happy.
If you want, you can look at my repositories.
https://github.com/familqasimov?tab=overview&from=2018-06-01&to=2018-06-30

Best regards.

**Comment by SloCompTech** [comment]
Hi,
I am happy that you are thinking to create logo for my projects. Feel free to design logos, because graphics design is my Achilles' heel, then create pull request. Note that I'm going on holiday tommorow so I will respond to any messages in fortnight.

**Comment by familqasimov** [comment]
Hi, sorry I've been ill for a few days now. But I've read what you wrote. I have a logo. But if you have any ideas, please write

![untitled-1](https://user-images.githubusercontent.com/36432269/43360544-2501e7e8-92c8-11e8-897b-0b507484b6eb.png)

**Comment by SloCompTech** [comment]
Very nice, which one do you prefer ?

**Comment by familqasimov** [comment]
Hi dear Martin. Logomark is our main logo and we can use it for the software. We can use the logo for the main background. 
an example of my other job: [screenshoot](https://user-images.githubusercontent.com/36432269/43851365-877bf09a-9b4b-11e8-972c-a5d022ca028c.jpeg)

**Comment by familqasimov** [comment]
Can I send you a PR?

**Comment by SloCompTech** [comment]
Yes please

**Comment by SloCompTech** [comment]
Thanks
